routes:
  /subscribe/: members/subscribe
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /upgrade/: members/upgrade
  /news/ : news

collections:
  /:
    permalink: /{slug}/
    template: index
  /rejections/:
    permalink: /rejections/{slug}/
    template: rejections
    filter: tag:rejections

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
